### ISSUE TITLE
Uncaught ReferenceError: django is not defined

### ISSUE THREAD

**Issue by blag** [theatlantic/django-ckeditor#8]
In ckeditor.js:
(function(m) {
   ...

})(django.jQuery);

The django.jQuery is undefined.

Am I missing something? Where is django.jQuery supposed to be defined?

Thanks for all the hard work!

**Comment by fdintino** [comment]
Try using the atl/4.1.x branch. That is the most up-to-date.

**Comment by blag** [comment]
That fixed it. Thanks for the help.
